package com.lebusishu.router

import com.lebusishu.example.MinorModule
import com.lebusishu.router.interfaces.IMirror
import java.util.HashMap
import kotlin.Any
import kotlin.String
import kotlin.Unit

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ANDROID ROUTER.
 */
public class kt_auto_android_minor : IMirror {
  public final val mapping: HashMap

  public final val original: Any
  init {
    this.original = MinorModule.class.newInstance()
    this.mapping = HashMap<Any?,Any?>()
    mapping.put("" +ModuleDelegater._METHOD,object.getClass().getMethod("def",android.app.Application.class,java.lang.String.class,com.lebusishu.router.VPromise.class))
    String args0 = "application,scheme,promise"
    mapping.put("" + ModuleDelegater._ARGS,args0)
    String type0 = "android.app.Application,java.lang.String,com.lebusishu.router.VPromise"
    mapping.put("" + ModuleDelegater._TYPES,type0)

    mapping.put("/activity/minoractivity" +ModuleDelegater._METHOD,object.getClass().getMethod("openMinorActivity",android.app.Application.class,com.lebusishu.router.VPromise.class))
    String args1 = "context,promise"
    mapping.put("/activity/minoractivity" + ModuleDelegater._ARGS,args1)
    String type1 = "android.app.Application,com.lebusishu.router.VPromise"
    mapping.put("/activity/minoractivity" + ModuleDelegater._TYPES,type1)

    mapping.put("/string/minoractivity" +ModuleDelegater._METHOD,object.getClass().getMethod("openMinorActivity",android.app.Application.class,java.lang.String.class,com.lebusishu.router.VPromise.class))
    String args2 = "context,param,promise"
    mapping.put("/string/minoractivity" + ModuleDelegater._ARGS,args2)
    String type2 = "android.app.Application,java.lang.String,com.lebusishu.router.VPromise"
    mapping.put("/string/minoractivity" + ModuleDelegater._TYPES,type2)

    mapping.put("/list/minoractivity" +ModuleDelegater._METHOD,object.getClass().getMethod("openMinorActivity",android.app.Application.class,java.util.ArrayList.class,com.lebusishu.router.VPromise.class))
    String args3 = "context,list,promise"
    mapping.put("/list/minoractivity" + ModuleDelegater._ARGS,args3)
    String type3 =
        "android.app.Application,java.util.ArrayList<java.lang.String>,com.lebusishu.router.VPromise"
    mapping.put("/list/minoractivity" + ModuleDelegater._TYPES,type3)

    mapping.put("/bean/minoractivity" +ModuleDelegater._METHOD,object.getClass().getMethod("openMinorActivity",android.app.Application.class,com.lebusishu.example.TestBean.class,com.lebusishu.router.VPromise.class))
    String args4 = "context,bean,promise"
    mapping.put("/bean/minoractivity" + ModuleDelegater._ARGS,args4)
    String type4 =
        "android.app.Application,com.lebusishu.example.TestBean,com.lebusishu.router.VPromise"
    mapping.put("/bean/minoractivity" + ModuleDelegater._TYPES,type4)

    mapping.put("/get/getdata" +ModuleDelegater._METHOD,object.getClass().getMethod("openGetData",com.lebusishu.router.VPromise.class))
    String args5 = "promise"
    mapping.put("/get/getdata" + ModuleDelegater._ARGS,args5)
    String type5 = "com.lebusishu.router.VPromise"
    mapping.put("/get/getdata" + ModuleDelegater._TYPES,type5)

    mapping.put("/get/getvalue" +ModuleDelegater._METHOD,object.getClass().getMethod("openGetValue",com.lebusishu.router.VPromise.class))
    String args6 = "promise"
    mapping.put("/get/getvalue" + ModuleDelegater._ARGS,args6)
    String type6 = "com.lebusishu.router.VPromise"
    mapping.put("/get/getvalue" + ModuleDelegater._TYPES,type6)

    mapping.put("/thread/getthread" +ModuleDelegater._METHOD,object.getClass().getMethod("openGetThread",com.lebusishu.router.VPromise.class))
    String args7 = "promise"
    mapping.put("/thread/getthread" + ModuleDelegater._ARGS,args7)
    String type7 = "com.lebusishu.router.VPromise"
    mapping.put("/thread/getthread" + ModuleDelegater._TYPES,type7)

    mapping.put("/autoreturn" +ModuleDelegater._METHOD,object.getClass().getMethod("openAutoReturn",com.lebusishu.router.VPromise.class))
    String args8 = "promise"
    mapping.put("/autoreturn" + ModuleDelegater._ARGS,args8)
    String type8 = "com.lebusishu.router.VPromise"
    mapping.put("/autoreturn" + ModuleDelegater._TYPES,type8)

    mapping.put("/complex/minoractivity" +ModuleDelegater._METHOD,object.getClass().getMethod("openComplexParams",android.app.Application.class,java.lang.String.class,java.util.ArrayList.class,com.lebusishu.example.TestBean.class,com.lebusishu.router.VPromise.class))
    String args9 = "application,param,list,bean,promise"
    mapping.put("/complex/minoractivity" + ModuleDelegater._ARGS,args9)
    String type9 =
        "android.app.Application,java.lang.String,java.util.ArrayList<java.lang.String>,com.lebusishu.example.TestBean,com.lebusishu.router.VPromise"
    mapping.put("/complex/minoractivity" + ModuleDelegater._TYPES,type9)

  }

  public operator fun invoke(path: String, params: ParamsWrapper): Unit {
    ModuleDelegater.Companion.invoke(path,params,object,mapping)
  }
}
